#支付服务模块
server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn_cloud?useUnicode=true&characterEncoding=utf-8&&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: password

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.learn.springcloud.entities    # 所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true。
    fetchRegistry: true   #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka #单机
      #defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版本
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示IP地址




